godfreyhomepage/dailycheckin/urls.py
from django.urls import path
from . import views

app_name = 'dailycheckin'

urlpatterns = [
    # The name is what is used for accessing this link from other areas so it would be
    # {{ % url 'users:register' % }}
    path('checkin/', views.check_in, name="checkin"),
    path('list/', views.checkin_list, name="checkin_list"),
    path('<slug:date_slug>/', views.checkin_details, name="checkin_detail"),

]

godfreyhomepage/godfreyhomepage/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
    path('dailycheckin/', include('dailycheckin.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

godfreyhomepage/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'


urlpatterns = [
    path('', views.posts_list, name="list"),
    path('<slug:slug>', views.post_page, name="page"),
]

godfreyhomepage/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    # The name is what is used for accessing this link from other areas so it would be
    # {{ % url 'users:register' % }}
    path('register/', views.register_user, name="register"),
]

godfreyhomepage/dailycheckin/models.py
from django.db import models
from django.forms import CharField
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils.text import slugify



# Create your models here.
class CheckIn(models.Model):
    #TODO DEBUG: CHANGE THIS BACK ONCE THEY SHOULDNT NEED TO INPUT THE DATE
    title = models.CharField(max_length=255)
    datetime = models.DateTimeField(auto_now_add=False)
    journal = models.CharField(max_length=2000)
    teeth = models.PositiveIntegerField(default=2, validators=[MinValueValidator(1), MaxValueValidator(2)])
    sleep = models.PositiveIntegerField()
    skincare = models.PositiveIntegerField()
    gym_hours = models.PositiveIntegerField()
    coding_hours = models.PositiveIntegerField()
    #TODO: This could be a sperate section with a current reads linking to the book in Q
    pages_read = models.PositiveIntegerField() 


    def __str__(self):
        return self.title
    
    @property
    def date_slug(self):
        return self.datetime.strftime('%Y-%m-%d')  # Generates the slug in the 'YYYY-MM-DD' format

godfreyhomepage/posts/models.py
from django.db import models

class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)

    def __str__(self):
        return self.title

godfreyhomepage/users/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=75)
    password = models.CharField(max_length=75)
    slug = models.SlugField()
    date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

godfreyhomepage/dailycheckin/forms.py
from django import forms
from .models import CheckIn
from datetime import datetime

class CheckInForm(forms.ModelForm):
    '''
    The Form for the Daily Checkins.
    To update you need to edit the model, add the feild to the list and add the widget 
    '''
    class Meta:
        model = CheckIn
        fields = ['datetime', 'title', 'journal', 'teeth', 'sleep', 'skincare', 'gym_hours', 'coding_hours', 'pages_read']
        widgets = {
            'datetime': forms.DateTimeInput(attrs={'class': 'form-control', 'type': 'datetime-local'}),
            'journal': forms.Textarea(attrs={'cols': 80, 'rows': 5}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'teeth': forms.NumberInput(attrs={'class': 'form-control'}),
            'sleep': forms.NumberInput(attrs={'class': 'form-control'}),
            'skincare': forms.NumberInput(attrs={'class': 'form-control'}),
            'gym_hours': forms.NumberInput(attrs={'class': 'form-control'}),
            'coding_hours': forms.NumberInput(attrs={'class': 'form-control'}),
            'pages_read': forms.NumberInput(attrs={'class': 'form-control'}),
        }

godfreyhomepage/dailycheckin/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .forms import CheckInForm
from .models import CheckIn

# Create your views here.
def check_in(request):
    if request.method == 'POST':
        form = CheckInForm(request.POST)
        if form.is_valid():
            # return redirect('dailycheckin/checkin:<slug:date_slug>') # TODO: This needs to be changed to a list of the check ins
            checkin_instance = form.save()  
            date_slug = checkin_instance.datetime.strftime('%Y-%m-%d')
            print(f"Redirecting to check-in detail for date_slug: {date_slug}")
            return redirect('dailycheckin:checkin_detail', date_slug=date_slug)  # Redirect to the detail page
    
    else:
        form = CheckInForm()

    return render(request, 'dailycheckin/checkin_form.html', {'form': form})

def checkin_details(request, date_slug):
    checkin = get_object_or_404(CheckIn, datetime__date=date_slug)
    return render(request, 'dailycheckin/checkin_detail.html', {'checkin': checkin})

def checkin_list(request):
    checkins = CheckIn.objects.all().order_by('-datetime')
    return render(request, 'dailycheckin/checkin_list.html', {'checkins': checkins})

godfreyhomepage/godfreyhomepage/views.py
from django.shortcuts import render

def homepage(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

godfreyhomepage/posts/views.py
from django.shortcuts import render
from .models import Post


# Create your views here.
def posts_list(requet):
    posts = Post.objects.all().order_by('-date')
    return render(requet, 'posts/posts_list.html', {'posts': posts})

def post_page(request, slug):
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html', {'post': post})

godfreyhomepage/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register_user(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else:
        form = UserCreationForm()
    return render(request, 'users/register_user.html', {"form": form})

godfreyhomepage/dailycheckin/templates/dailycheckin/checkin_detail.html
{% extends "layout.html" %}

{% block title %}
    {{ checkin.title }}
{% endblock title %}

{% block content %}
    <section>
        <a href="{% url 'dailycheckin:checkin_list' %}">
            <span role="img" aria-label="Home" title="CheckIn-List">Go to List</span>
        </a>
    </section>
    <section>
        <h1>{{ checkin.title }}</h1>
        <p><strong>Date:</strong> {{ checkin.datetime|date:"F j, Y, g:i a" }}</p>
        <p><strong>Journal Entry:</strong> {{ checkin.journal }}</p>
        <p><strong>Teeth Brushed:</strong> {{ checkin.teeth }}</p>
        <p><strong>Sleep (Hours):</strong> {{ checkin.sleep }}</p>
        <p><strong>Skincare Done:</strong> {{ checkin.skincare }}</p>
        <p><strong>Gym Hours:</strong> {{ checkin.gym_hours }}</p>
        <p><strong>Coding Hours:</strong> {{ checkin.coding_hours }}</p>
        <p><strong>Pages Read:</strong> {{ checkin.pages_read }}</p>
    </section>
{% endblock content %}

godfreyhomepage/dailycheckin/templates/dailycheckin/checkin_form.html
{% extends "layout.html" %}

{% block title %}
    Start you Daily Check-in
{% endblock title %}

{% block content %}
    <div class="container mt-5 pb-4">
        <h1>Start you Daily Check-in</h1>
        <form method="post">

            {% csrf_token %}
            <div class="mb-3">
                <label for="id_datetime" class="form-label">Date and Time</label>
                {{ form.datetime }}
            </div>
            
            <div class="mb-3">
                <label for="id_title" class="form-label">Title</label>
                {{ form.title }}
            </div>
            
            <div class="mb-3">
                <label for="id_journal" class="form-label">Journal</label>
                <textarea name="journal" id="id_journal" class="form-control" cols="80" rows="5">{{ form.journal.value }}</textarea>
            </div>
            
            <div class="mb-3">
                <label for="id_teeth" class="form-label">Teeth</label>
                {{ form.teeth }}
            </div>
            
            <div class="mb-3">
                <label for="id_sleep" class="form-label">Sleep (hours)</label>
                {{ form.sleep }}
            </div>
            
            <div class="mb-3">
                <label for="id_skincare" class="form-label">Skincare (hours)</label>
                {{ form.skincare }}
            </div>
            
            <div class="mb-3">
                <label for="id_gym_hours" class="form-label">Gym Hours</label>
                {{ form.gym_hours }}
            </div>
            
            <div class="mb-3">
                <label for="id_coding_hours" class="form-label">Coding Hours</label>
                {{ form.coding_hours }}
            </div>
            
            <div class="mb-3">
                <label for="id_pages_read" class="form-label">Pages Read</label>
                {{ form.pages_read }}
            </div>
            <button class="justify-content-center" type="submit">Submit</button>
        </div>
        </form>
    </div>
{% endblock content %}

godfreyhomepage/dailycheckin/templates/dailycheckin/checkin_list.html
{% extends "layout.html" %}

{% block title %}
    Checkins
{% endblock title %}

{% block content %}
<section class="p-2">
    <a  href="{% url 'dailycheckin:checkin' %}">
        <strong>Daily Checkin</strong>
    </a>
</section>


<section class="p-2">
    {% for checkin in checkins %}
        <article class="post">
            <h2>
                <a href="{% url 'dailycheckin:checkin_detail' date_slug=checkin.datetime|date:"Y-m-d" %}">
                    {{ checkin.title }}
                </a>
            </h2>
            <p>{{ checkin.datetime }}</p>
        </article>
    {% endfor %}
</section>
{% endblock content %}

godfreyhomepage/posts/templates/posts/post_page.html
{% extends "layout.html" %}

{% block title %}
    {{ post.title }}
{% endblock title %}

{% block content %}
    <section>
        <img 
            class ="banner"
            src="{{ post.banner.url }}" 
            alt="{{ post.title }}"
        />
        <h1>{{ post.title }}</h1>
        <p>{{ post.date }}</p>
        <p>{{ post.body }}</p>
    </section>
{% endblock content %}

godfreyhomepage/posts/templates/posts/posts_list.html
{% extends "layout.html" %}

{% block title %}
    Post Lists
{% endblock title %}

{% block content %}
<section>
    <h1>Posts List</h1>
    {% for post in posts %}
        <article class="post">
            <h2>
                <a href="{% url 'posts:page' slug=post.slug %}">
                    {{ post.title }}
                </a>
                
            </h2>
            <p>{{ post.date }}</p>
            <p>{{ post.body }}</p>
        </article>
    {% endfor %}
</section>
{% endblock content %}

godfreyhomepage/templates/about.html
{% extends "layout.html" %}

{% block title %}
    About
{% endblock title %}

{% block content %}
    <h1>About</h1>
    <p>Checkout my <a href="/">Home</a></p>
{% endblock content %}

godfreyhomepage/templates/home.html
{% extends "layout.html" %}

{% block title %}
    Home
{% endblock title %}

{% block content %}
    <h1>Home</h1>
    <p>Checkout my <a href="/about">About Page</a></div></p>
{% endblock content %}

godfreyhomepage/templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load bootstrap5 %}
    {% bootstrap_css %}
    {% bootstrap_javascript %}
    <script src="{% static 'js/main.js' %}" defer></script>
    <title>
        {% block title %}{% endblock %}
    </title>
</head>
<body>
    <nav class="nav nav-tabs bg-info justify-content-center">
        <li class="nav item">
            <a class="nav-link {% if request.path == '/' %}active{% endif %}" href="/">Home</a>
        </li>
        <li class="nav item">
            <a class="nav-link {% if request.path == '/about/' %}active{% endif %}" href="/about">About</a>
        </li>
        <li class="nav item">
            <a class="nav-link {% if request.resolver_match.url_name == 'list' %}active{% endif %}" href="{% url 'posts:list' %}">Posts</a> 
        </li>
        <li class="nav item">
            <a class="nav-link {% if request.resolver_match.url_name == 'register' %}active{% endif %}" href="{% url 'users:register' %}">Users</a>
        </li>
        <li class="nav item">
            <a class="nav-link {% if request.resolver_match.url_name == 'checkin_list' %}active{% endif %}"  href="{% url 'dailycheckin:checkin_list' %}">Daily Checkin</a>
        </li>
    </nav>
    <main>
        {% block content%}
        {% endblock %}
    </main>
</body>
</html>

godfreyhomepage/users/templates/users/register_user.html
{% extends "layout.html" %}

{% block title %}
    Register a new User
{% endblock title %}

{% block content %}
    <h1>Register a New User</h1>
    <form class="form-with-validation" action="/users/register/" method="post">
        {% csrf_token %}
        {{ form }}
        <button class="form-submit"> Submit </button>
    </form>
{% endblock content %}